celestiaorg/helm-charts

- charts/celestia-node/templates/service.yaml
- charts/celestia-node/templates/statefulset.yaml
Enable `udp` protocol for `celestia-node`
> Add `udp` protocol

- charts/celestia-app/Chart.yaml
- charts/celestia-app/README.md
- charts/celestia-app/values.yaml
- charts/celestia-node/Chart.yaml
- charts/celestia-node/README.md
- charts/celestia-node/templates/configmap.yaml
- charts/celestia-node/values.yaml
- scripts/config/app/v1.11.0/app.toml
- scripts/config/app/v1.11.0/client.toml
- scripts/config/app/v1.11.0/config.toml
- scripts/config/node/v0.13.7/config.toml
- scripts/config/node/v0.14.0/config.toml
> Smuu/bump node to v0.14.0 and app to v0.11.0

- charts/celestia-app/Chart.yaml
- charts/celestia-node/Chart.yaml
> feat: new app and node release

- README.md
> bugfix: readme repo url

- .github/workflows/releaser.yaml
Upload chart packages directly into publishing branch.
https://github.com/helm/chart-releaser-action
> Helm releases with index

- charts/celestia-app/Chart.yaml
- charts/celestia-node/Chart.yaml
> feat: bump to create a release

- charts/celestia-node/Chart.yaml
> feat: bump node to 1.1

- charts/celestia-app/Chart.yaml
> feat: bump app to 1.1

- charts/celestia-node/templates/role.yaml
- charts/celestia-node/templates/rolebinding.yaml
> bugfix: rbac role

- charts/celestia-node/Chart.yaml
- charts/celestia-node/templates/NOTES.txt
- charts/celestia-node/templates/_helpers.tpl
- charts/celestia-node/templates/statefulset.yaml
> fix: correct use args and extraArgs

- charts/celestia-node/Chart.yaml
- charts/celestia-node/values.yaml
> fix: use proper 0.16.0 version

- charts/celestia-app/Chart.yaml
- charts/celestia-app/values.yaml
> fix: app version

- charts/celestia-app/README.md
- charts/celestia-node/Chart.yaml
- charts/celestia-node/README.md
- charts/celestia-node/templates/statefulset.yaml
- charts/celestia-node/values.yaml
- scripts/config/node/bridge/v0.16.1/config.toml
- scripts/config/node/full/v0.16.1/config.toml
- scripts/config/node/light/v0.16.1/config.toml
- scripts/extract_configs.sh
> feat(node): bump to v0.16.1

- charts/celestia-node/Chart.yaml
- charts/celestia-node/templates/statefulset.yaml
> fix: yaml json

- .github/workflows/releaser.yaml
- charts/celestia-node/Chart.yaml
- charts/celestia-node/README.md
- charts/celestia-node/values.yaml
- scripts/config/node/bridge/v0.16.2/config.toml
- scripts/config/node/full/v0.16.2/config.toml
- scripts/config/node/light/v0.16.2/config.toml
> feat(node): bump to v0.16.2

- charts/celestia-node/templates/statefulset.yaml
Closes https://github.com/celestiaorg/devops/issues/972
> feat: remove not needed folders after shawap

- charts/celestia-node/Chart.yaml
- charts/celestia-node/templates/statefulset.yaml
> fix: templating

- charts/celestia-node/values.yaml
Closes https://github.com/celestiaorg/helm-charts/issues/49
> feat: minimal default config for otel

- charts/celestia-node/templates/configmap-otel-agent.yaml
- charts/celestia-node/values.yaml
Closes https://github.com/celestiaorg/devops/issues/986
> feat(node): allow custom otel config

- charts/celestia-app/Chart.yaml
- charts/celestia-node/Chart.yaml
> feat(app/node): create patch releases

- charts/celestia-node/templates/configmap-otel-agent.yaml
> fix(node): otel agent template

- charts/celestia-node/Chart.yaml
> feat(node): patch 0.5.4

- charts/celestia-app/templates/_helpers.tpl
- charts/celestia-app/values.yaml
- charts/celestia-node/templates/_helpers.tpl
- charts/celestia-node/templates/statefulset.yaml
- charts/celestia-node/values.yaml
- value to skip validation
- value to disable hostPort
- other fixes
> feat: Skip Validation, Disable HostPort, and Misc Fixes

- scripts/config/node/bridge/v0.20.3-arabica/config.toml
- scripts/config/node/full/v0.20.3-arabica/config.toml
- scripts/config/node/light/v0.20.3-arabica/config.toml
> feat: upgrade node to v0.20.3

- charts/celestia-node/Chart.yaml
- charts/celestia-node/values.yaml
- scripts/config/node/bridge/v0.20.3-arabica/config.toml
- scripts/config/node/full/v0.20.3-arabica/config.toml
- scripts/config/node/light/v0.20.3-arabica/config.toml
> 20241126 node release v0 20 3

- charts/celestia-node/Chart.yaml
- charts/celestia-node/values.yaml
- Config had a breaking change
- It seems that only bridge and full was upgraded
- this PR adds the change to light as well
> fix: light node config
